/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.org.vikingsoftware.dropshipper.listing.tool.gui;

/**
 *
 * @author Bren
 */
public class ListingToolGUI extends javax.swing.JFrame {

	private static final long serialVersionUID = 7954579463528571026L;

	private static ListingToolGUI instance;
	private static ListingToolController controller;

	/**
     * Creates new form GUI
     */
    private ListingToolGUI() {
        initComponents();
    }

    public static synchronized ListingToolGUI get() {
    	if(instance == null) {
    		instance = new ListingToolGUI();
    		controller = new ListingToolController();
    		controller.addListeners();
    	}

    	return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagesScrollPane = new javax.swing.JScrollPane();
        imagesPanel = new javax.swing.JPanel();
        fulfillmentUrlInput = new javax.swing.JTextField();
        fullfillmentFileBtn = new javax.swing.JButton();
        variationsHeaderText = new javax.swing.JLabel();
        variationsScrollPane = new javax.swing.JScrollPane();
        variationsTable = new javax.swing.JTable();
        imagesHeaderText = new javax.swing.JLabel();
        generalInformationHeaderText1 = new javax.swing.JLabel();
        listingTitleInput = new javax.swing.JTextField();
        listingTitleHeaderText = new javax.swing.JLabel();
        categoryTitleHeaderText = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox();
        descriptionTitleHeaderText = new javax.swing.JLabel();
        renderedDescScrollPane = new javax.swing.JScrollPane();
        renderedDescPane = new javax.swing.JEditorPane();
        rawDescScrollPane = new javax.swing.JScrollPane();
        rawDescInput = new javax.swing.JTextArea();
        addFullfillmentHeaderText = new javax.swing.JLabel();
        fullfillmentsTitleHeaderText = new javax.swing.JLabel();
        queueSizeValue = new javax.swing.JLabel();
        queueSizeLabelText = new javax.swing.JLabel();
        skipListingBtn = new javax.swing.JButton();
        publishListingBtn = new javax.swing.JButton();
        statusText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1225, 825));
        getContentPane().setLayout(null);

        imagesScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        final javax.swing.GroupLayout imagesPanelLayout = new javax.swing.GroupLayout(imagesPanel);
        imagesPanel.setLayout(imagesPanelLayout);
        imagesPanelLayout.setHorizontalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        imagesPanelLayout.setVerticalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        imagesScrollPane.setViewportView(imagesPanel);

        getContentPane().add(imagesScrollPane);
        imagesScrollPane.setBounds(10, 210, 382, 570);

        fulfillmentUrlInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fulfillmentUrlInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        fulfillmentUrlInput.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulfillmentUrlInputActionPerformed(evt);
            }
        });
        getContentPane().add(fulfillmentUrlInput);
        fulfillmentUrlInput.setBounds(10, 62, 310, 30);

        fullfillmentFileBtn.setBackground(new java.awt.Color(51, 51, 51));
        fullfillmentFileBtn.setText("file");
        fullfillmentFileBtn.setBorder(null);
        fullfillmentFileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fullfillmentFileBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullfillmentFileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(fullfillmentFileBtn);
        fullfillmentFileBtn.setBounds(322, 62, 50, 30);

        variationsHeaderText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        variationsHeaderText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        variationsHeaderText.setText("Variations");
        variationsHeaderText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(variationsHeaderText);
        variationsHeaderText.setBounds(820, 10, 110, 24);

        variationsScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        variationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Price", "Color", "Length"
            }
        ));
        variationsScrollPane.setViewportView(variationsTable);

        getContentPane().add(variationsScrollPane);
        variationsScrollPane.setBounds(820, 40, 370, 160);

        imagesHeaderText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        imagesHeaderText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imagesHeaderText.setText("Images");
        imagesHeaderText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(imagesHeaderText);
        imagesHeaderText.setBounds(10, 180, 70, 24);

        generalInformationHeaderText1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        generalInformationHeaderText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        generalInformationHeaderText1.setText("General information");
        generalInformationHeaderText1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(generalInformationHeaderText1);
        generalInformationHeaderText1.setBounds(390, 10, 170, 24);

        listingTitleInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        getContentPane().add(listingTitleInput);
        listingTitleInput.setBounds(390, 62, 420, 40);

        listingTitleHeaderText.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        listingTitleHeaderText.setText("TITLE");
        getContentPane().add(listingTitleHeaderText);
        listingTitleHeaderText.setBounds(390, 45, 34, 14);

        categoryTitleHeaderText.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        categoryTitleHeaderText.setText("CATEGORY");
        getContentPane().add(categoryTitleHeaderText);
        categoryTitleHeaderText.setBounds(390, 122, 70, 14);

        categoryBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        getContentPane().add(categoryBox);
        categoryBox.setBounds(390, 140, 420, 30);

        descriptionTitleHeaderText.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        descriptionTitleHeaderText.setText("DESCRIPTION");
        getContentPane().add(descriptionTitleHeaderText);
        descriptionTitleHeaderText.setBounds(390, 190, 80, 14);

        renderedDescScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        renderedDescPane.setBorder(null);
        renderedDescPane.setContentType("text/html"); // NOI18N
        renderedDescPane.setText("<p>Lorem ipsum dolor sit amet.</p>");
        renderedDescScrollPane.setViewportView(renderedDescPane);

        getContentPane().add(renderedDescScrollPane);
        renderedDescScrollPane.setBounds(390, 390, 810, 390);

        rawDescScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        rawDescInput.setColumns(20);
        rawDescInput.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        rawDescInput.setRows(5);
        rawDescInput.setText("<p>Lorem ipsum dolor sit amet.</p>");
        rawDescScrollPane.setViewportView(rawDescInput);

        getContentPane().add(rawDescScrollPane);
        rawDescScrollPane.setBounds(390, 210, 810, 182);

        addFullfillmentHeaderText.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        addFullfillmentHeaderText.setText("ADD FULLFILLMENT URL TO QUEUE");
        getContentPane().add(addFullfillmentHeaderText);
        addFullfillmentHeaderText.setBounds(10, 45, 200, 14);

        fullfillmentsTitleHeaderText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fullfillmentsTitleHeaderText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fullfillmentsTitleHeaderText.setText("Fullfillments");
        fullfillmentsTitleHeaderText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(fullfillmentsTitleHeaderText);
        fullfillmentsTitleHeaderText.setBounds(10, 10, 170, 24);

        queueSizeValue.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        queueSizeValue.setForeground(new java.awt.Color(0, 0, 255));
        queueSizeValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        queueSizeValue.setText("0");
        getContentPane().add(queueSizeValue);
        queueSizeValue.setBounds(342, 45, 30, 14);

        queueSizeLabelText.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        queueSizeLabelText.setText("Queue size:");
        getContentPane().add(queueSizeLabelText);
        queueSizeLabelText.setBounds(278, 45, 70, 14);

        skipListingBtn.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        skipListingBtn.setForeground(new java.awt.Color(255, 0, 0));
        skipListingBtn.setText("Skip Listing");
        skipListingBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        skipListingBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipListingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(skipListingBtn);
        skipListingBtn.setBounds(165, 143, 70, 34);

        publishListingBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        publishListingBtn.setForeground(new java.awt.Color(0, 153, 0));
        publishListingBtn.setText("Publish Listing");
        publishListingBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        publishListingBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishListingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(publishListingBtn);
        publishListingBtn.setBounds(240, 140, 135, 40);

        statusText.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        statusText.setText("AliExpressParser: Scraping images (2/6)");
        statusText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(statusText);
        statusText.setBounds(10, 95, 360, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullfillmentFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullfillmentFileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullfillmentFileBtnActionPerformed

    private void fulfillmentUrlInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulfillmentUrlInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fulfillmentUrlInputActionPerformed

    private void skipListingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipListingBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skipListingBtnActionPerformed

    private void publishListingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishListingBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publishListingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (final ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListingToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListingToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListingToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListingToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new ListingToolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel addFullfillmentHeaderText;
    public javax.swing.JComboBox categoryBox;
    public javax.swing.JLabel categoryTitleHeaderText;
    public javax.swing.JLabel descriptionTitleHeaderText;
    public javax.swing.JTextField fulfillmentUrlInput;
    public javax.swing.JButton fullfillmentFileBtn;
    public javax.swing.JLabel fullfillmentsTitleHeaderText;
    public javax.swing.JLabel generalInformationHeaderText1;
    public javax.swing.JLabel imagesHeaderText;
    public javax.swing.JPanel imagesPanel;
    public javax.swing.JScrollPane imagesScrollPane;
    public javax.swing.JLabel listingTitleHeaderText;
    public javax.swing.JTextField listingTitleInput;
    public javax.swing.JButton publishListingBtn;
    public javax.swing.JLabel queueSizeLabelText;
    public javax.swing.JLabel queueSizeValue;
    public javax.swing.JTextArea rawDescInput;
    public javax.swing.JScrollPane rawDescScrollPane;
    public javax.swing.JEditorPane renderedDescPane;
    public javax.swing.JScrollPane renderedDescScrollPane;
    public javax.swing.JButton skipListingBtn;
    public javax.swing.JLabel statusText;
    public javax.swing.JLabel variationsHeaderText;
    public javax.swing.JScrollPane variationsScrollPane;
    public javax.swing.JTable variationsTable;
    // End of variables declaration//GEN-END:variables
}
